########################
# Load config file
########################
configfile: "configs/configuser.yaml"

#Define samples can be extracted by func
SAMPLES=["A","B","C"]
#path to qc in the project
QCPATH= config["workdir"]+"/"+config["projectname"]+"/qc/fastqc"


##########################
# Rules definition
##########################
rule prj_tree:
	priority: 10
	params:
		projectname=config["projectname"],
		workdir=config["workdir"]

	message: "Step1: Create project tree."
	log: "logs/prjtree.log"
	shell:
		r"""
		python  scripts/prjtree.py {params.projectname} {params.workdir} 
		sleep 5
		"""

rule mini_report:
	priority: 1
	params:
		username=config["username"],
		projectname=config["projectname"],
		workdir=config["workdir"],
		datadir=config["datadir"]
	message: "Step2: Create the mini report."
	log: "logs/minireport.log"
	shell:
		r"""python  scripts/minireport.py {params.username} {params.projectname} {params.workdir} {params.datadir}
		sleep 5
		"""

rule clean_all:
	priority: 2
	params:
		projectname=config["projectname"],
		workdir=config["workdir"]
	message: "Step4: Move logs to Project Logs"
	shell:
		r"""
		sleep 5
		mv logs {params.workdir}/{params.projectname}/Logs/
		"""

##################
#Quality controle
##################
include: 'rules/qc.smk'
